class DataValidationError(ValueError):
    """Custom exception for validation errors."""
    pass

class DataProcessError(ValueError):
    """Custom exception for validation errors."""
    pass