
class DataProcessError(ValueError):
    """Custom exception for validation errors."""
    pass